### ISSUE TITLE
Autofill not working on Brave Browser on iOS

### ISSUE THREAD

**Issue by MooseExplorer637** [strongbox-password-safe/Strongbox#734]
The iOS autofill works flawlessly with Safari, but with the Brave Browser, instead of filling out the username and password, the browser freezes completely. I have also tested this with Bitwarden, and there is no similar issue, so the problem has to be with Strongbox.

**Comment by Slummi** [comment]
I've also had this problem for a while, but with almost all apps and browsers.
It always occurs when I select an AutoFill suggestion that is displayed directly above the keyboard.
If I use AutoFill via the key button, it works.

**Comment by strongbox-mark** [comment]
Hi @MooseExplorer637 - This seems like a duplicate for #729 - Could you also please provide version information when you report bugs?

What version of iOS are you running? Strongbox? Brave? 

Similarly @Slummi - Versions please. Thanks!

**Comment by Slummi** [comment]
I'm using the latest Strongbox stable release (1.58.28 (4614)@da0076a-P) on iOS 17.1 (iPhone 15 Pro).

I had that issue also with earlier versions of Strongbox and iOS and also on older devices.

I think the issue first occured with the first version with PassKeys support.

**Comment by strongbox-mark** [comment]
Hi @Slummi - I can't seem to reproduce the issue on this side given those versions. Could you give an example App and version you see this on, and also, what is your database file size and argon2 parameters?

**Comment by MooseExplorer637** [comment]
@strongbox-mark The whole site started to magically work when I created this new login. Not only did the new login work, but also the older login that hadn't previously worked. After this, I also tried to delete that new login, and even then, the old login is now working.

**Comment by strongbox-mark** [comment]
That's so strange, thanks for the update... By the way, we still have some others with issues, like this. One question, do you use a Key File?

**Comment by strongbox-mark** [comment]
Thanks, please let me know if the issue re-occurs :)

**Comment by MooseExplorer637** [comment]
It just did... Tried it again, and the issue is back again :(

**Comment by strongbox-mark** [comment]
OK, thanks, would mind sending your debug info to support@strongboxsafe.com?

**Comment by Slummi** [comment]
> Hi @Slummi - I can't seem to reproduce the issue on this side given those versions. Could you give an example App and version you see this on, and also, what is your database file size and argon2 parameters?

Unfortunately I can't reproduce the issue at the moment either.
Yesterday it was still there in different apps (e.g. PayPal) and browsers. When the issue occurs, the behavior is similar to #729. After selecting the suggested AutoFill credentials (QuickType) and authenticating via FaceID there's a gray shadow on the app / browser and it freezes. Using the key button instead of the QuickType suggestion always works.

I've no idea why it's currently working. Perhaps because the latest changes on the database were done by KeePass (Windows)?!

My database has 5.1 MB.
Argon2d settings:
Memory 8 MB
Iterations 130
Parallelism 2

**Comment by strongbox-mark** [comment]
I've released an update (1.58.29) available on the App Store now, which I'm hoping will improve things, and I'd love some feedback. Could you guys update and let me know?

You might need to search on the App Store for Strongbox and click/tap into it to see the "Update" button, as it might not update automatically.

**Comment by MooseExplorer637** [comment]
I have only tested this with two sites that I have had problems with, and with the other one, the update seems to have fixed the issue, while with the other one, I now get this.
![IMG_0922](https://github.com/strongbox-password-safe/Strongbox/assets/129966211/bbecea5c-4846-44cb-943b-e43a26f8e14e)

**Comment by strongbox-mark** [comment]
OK, that doesn't really seem great. Are you saying that 2 sites now work, and 1 doesn't or that 1 site works and the other doesn't?

Also, this might be due to some caching, does a full device restart help?

**Comment by MooseExplorer637** [comment]
I mean that 1 site works now which didn't previously, and the other site doesn't, although, the site that doesn't work didn't work either previously. I also did a full device restart, but that didn't solve this issue.

**Comment by strongbox-mark** [comment]
OK, thanks @MooseExplorer637 - back to the drawing board...

**Comment by strongbox-mark** [comment]
Hi @MooseExplorer637 -  Could you update to 1.58.35 and let me know if this fixes things for you?

**Comment by MooseExplorer637** [comment]
Yes, it seems that the latest version has fixed the issue. Thank you!
